language: php
php:
- 7.0
branches:
  only:
  - master
    - /^\d+\.\d+$/
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
- chmod +x $TRAVIS_BUILD_DIR/scripts/travis/before_install.sh
- "$TRAVIS_BUILD_DIR/scripts/travis/before_install.sh"
script:
- chmod +x $TRAVIS_BUILD_DIR/scripts/travis/build.sh
- "$TRAVIS_BUILD_DIR/scripts/travis/build.sh"