language: php
php:
- 7.0
branches:
  only:
  - master
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 2.0
  - 3.0
  - feature/349-travis
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
- chmod +x $TRAVIS_BUILD_DIR/scripts/travis/before_install.sh
- "$TRAVIS_BUILD_DIR/scripts/travis/before_install.sh"
script:
- chmod +x $TRAVIS_BUILD_DIR/scripts/travis/build.sh
- "$TRAVIS_BUILD_DIR/scripts/travis/build.sh"